In [1]:
import numpy as np

In [2]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [3]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [4]:
ar = np.array([[1,2,3], [4,5,6]])

In [5]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
ar * ar

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
arr = np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5:8] == 12

array([False, False, False])

In [14]:
arr[5:8] = 12

In [15]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [18]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [19]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2d[1]

array([4, 5, 6])

In [21]:
arr2d[1,2]

6

In [23]:
arr2d[1:1]

array([], shape=(0, 3), dtype=int64)

In [24]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [28]:
arr3d.shape

(2, 2, 3)

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0].shape

(2, 3)

In [31]:
arr3d[1,0]

array([7, 8, 9])

In [33]:
import numpy as np
import pandas as pd

In [34]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33, 11.44, 33.21, 13.23, 33.62]})

In [35]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'color': ['white','red','red','black']})

#### Nota: ambos dataframes tiene una columna con la misma etiqueta: 'id'.

In [36]:
# aplicamos la función merge simplemente, sin especificar nada en el dódigo
# f3 es una unión de los dos dataframes incluidos en la funcion merge, unidos por su columna común

f3 = pd.merge(frame1, frame2)

In [37]:
f3
# IMPORTANTE!!!!!: EL RESULTADO DE merge() ES QUE DEVUELVE SOLO LAS FILAS QUE TIENEN UNA ETIQUETA DE 'id' COMUN.
#                  LAS DEMAS NO APARECEN EN EL DATAFRAME RESULTADO f3.

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

## OTRO EJEMPLO:

In [38]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'color': ['white','red','red','black','green'], 
                        'brand': ['OMG','ABC','ABC','POD','POD']})

In [39]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'], 
                        'brand': ['OMG','POD','ABC','POD']})

In [40]:
# tenemos dos df con dos columnas con el mismo nombre. Si utilizamos merge sin especificaciones, la función no sabría 
# en que basar la unión.
# como se ve en el resultado, se obtiene una estructura vacía.
f3 = pd.merge(frame1, frame2)

In [41]:
f3

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [42]:
pd.merge(frame1, frame2, on='id')
# especificando explicitamente en que columna debe referirse la unión con la opción on.
# nuevamente puede verse que solo aparecen en el resultado las "filas" comunes según el criterio elegido.

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [43]:
# si elegimos otro criterio de unión (o fusión) obtendremos otra estructura como resultado
# en la estructura que resulta aparencen todas las filas que pueden obtenerse combinando ambas estructuras. 
# frame1 tiene 5 filas y frame dos tiene 4, pero el resultado tiene 7 filas; por ejemplo con 'OMG' pude realizarse 
# solo una unión: ball, white, OMG pencil.
# con 'ABC' se puede fusionar (pencil, red, ABC , ball) y (pen, red, ABC, ball)
# con 'POD': (mug, black, POD, pencil), (ashtry, green, POD, pencil), (mug, black, POD, pen), (ashtry, green, POD,pen)

pd.merge(frame1, frame2, on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [44]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [45]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [55]:
# la siguiente instrucción le cambia el nombre a las columnas
frame2.columns = ['sid', 'brand']

In [56]:
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [58]:
# no se podria fusionar las estructuras por no contener una columna en común
pd.merge(frame1, frame2, left_on='id', right_on='sid')

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

In [60]:
frame1.merge(frame2, left_on='id', right_on='sid')

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

In [50]:
frame2.columns=['brand','id']

In [54]:
pd.merge(frame1, frame2, on='id', how='outer')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN
5      OMG    NaN     NaN  pencil
6      POD    NaN     NaN  pencil
7      POD    NaN     NaN     pen
8      ABC    NaN     NaN    ball

In [52]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [53]:
frame2

brand   id
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [63]:
frame2.columns=['id', 'brand']

In [64]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [66]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [68]:
# pone una estructura al lado de la otra con la columna 'id' como referencia
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [73]:
# podemos usar la función join()
# primero renombramos las columnas porque join da error si hay columnas con etiquetas iguales
frame2.columns=['brand2', 'id2']

In [74]:
frame2

brand2  id2
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [75]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [77]:
frame1.join(frame2)
# puso una estructura al lado de la otra. con las filas compartiendo datos

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

In [78]:
# que pasa si cambiamos el orde, es decir, intercambiamos el nombre de las columnas de frame2
frame2.columns = ['id2', 'brand2']

In [79]:
frame1.join(frame2)

id  color brand     id2 brand2
0     ball  white   OMG  pencil    OMG
1   pencil    red   ABC  pencil    POD
2      pen    red   ABC    ball    ABC
3      mug  black   POD     pen    POD
4  ashtray  green   POD     NaN    NaN

#### CONCATENACION

In [80]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])

In [81]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])

In [82]:
ser1

1    0.104877
2    0.431572
3    0.651459
4    0.075673
dtype: float64

In [83]:
ser2

5    0.949711
6    0.071809
7    0.459258
8    0.239045
dtype: float64

In [84]:
pd.concat([ser1, ser2])

1    0.104877
2    0.431572
3    0.651459
4    0.075673
5    0.949711
6    0.071809
7    0.459258
8    0.239045
dtype: float64

In [93]:
# por defecto axis = 0, pero si usamos axis=1 (por columnas), también puede verse que la unión no se superpone una
# con otro, porque la caractericita join=outer (por fuera,  hacia afuera).
pd.concat([ser1, ser2], axis=1)

0         1
1  0.104877       NaN
2  0.431572       NaN
3  0.651459       NaN
4  0.075673       NaN
5       NaN  0.949711
6       NaN  0.071809
7       NaN  0.459258
8       NaN  0.239045

In [98]:
pd.concat([ser1, ser2], keys=[1,2])

1  1    0.104877
   2    0.431572
   3    0.651459
   4    0.075673
2  5    0.949711
   6    0.071809
   7    0.459258
   8    0.239045
dtype: float64

In [105]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], columns=['A','B','C'])

In [106]:
frame1

A         B         C
1  0.909970  0.687469  0.857723
2  0.488282  0.465210  0.290635
3  0.694136  0.790107  0.490891

In [107]:
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], columns=['A','B','C'])

In [108]:
frame2

A         B         C
4  0.000482  0.127102  0.078429
5  0.052992  0.574241  0.257657
6  0.981426  0.672809  0.932586

In [109]:
# como axis=0 por defecto, la función pone las estructuras una arriba de la otra, en filas
pd.concat([frame1, frame2])

A         B         C
1  0.909970  0.687469  0.857723
2  0.488282  0.465210  0.290635
3  0.694136  0.790107  0.490891
4  0.000482  0.127102  0.078429
5  0.052992  0.574241  0.257657
6  0.981426  0.672809  0.932586

In [110]:
# para colocar las estructuras una al lado de la otra, en columnas, axis=1, los lugares vaciós se completan con NaN
pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.909970  0.687469  0.857723       NaN       NaN       NaN
2  0.488282  0.465210  0.290635       NaN       NaN       NaN
3  0.694136  0.790107  0.490891       NaN       NaN       NaN
4       NaN       NaN       NaN  0.000482  0.127102  0.078429
5       NaN       NaN       NaN  0.052992  0.574241  0.257657
6       NaN       NaN       NaN  0.981426  0.672809  0.932586

In [111]:
# si le cambiamos los nombres de las filas a frame2, para que tengan el mismo nombre que las de frame1
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], columns=['A','B','C'])

In [112]:
frame2

A         B         C
1  0.701916  0.375370  0.655572
2  0.571405  0.742052  0.201560
3  0.426775  0.153111  0.916228

In [113]:
pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.909970  0.687469  0.857723  0.701916  0.375370  0.655572
2  0.488282  0.465210  0.290635  0.571405  0.742052  0.201560
3  0.694136  0.790107  0.490891  0.426775  0.153111  0.916228

In [6]:
import numpy as np
import pandas as pd

In [7]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [8]:
frame = pd.DataFrame(data)

In [9]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [10]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [11]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [12]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [13]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [14]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [16]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [19]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [21]:
frame2̈́['debt'] = np.arange(6.)

NameError: name 'frame2̈́' is not defined

In [23]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [25]:
val = pd.Series([-1.2, -1.5, -1.7], index=['uno', 'dos', 'tres'])

In [26]:
val

uno    -1.2
dos    -1.5
tres   -1.7
dtype: float64

In [28]:
frame2['debt'] = val

In [29]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [31]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [33]:
# Si el diccionario anidado se pasa al DataFrame, pandas interpretará las claves del diccionario externo como columnas 
# y las claves internas como índices de fila:

populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [34]:
# transposición, intercambio de filas y columnas
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [39]:
# NOTAR en la salida de esta instrucción: para 2003, no hay datos y pandas actúa en consecuencia al definir los índices
pd.DataFrame(populations, index=[2001, 2002, 2003])             

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [ ]:
# diccionarios de series